### ISSUE TITLE
Add minimum privileges for Jamf API User to Wiki

### ISSUE THREAD

**Issue by chrisgrande** [alectrona/git4jamfpro#2]
I'm using just Create/Read/Update for EAs and Scripts, and everything seems to be fine.

**Comment by ryangball** [comment]
That is a good suggestion @chrisgrande!

**Comment by ryangball** [comment]
This has been added to both the README and the Wiki:

- https://github.com/alectrona/git4jamfpro#required-permissions
- https://github.com/alectrona/git4jamfpro/wiki/Pushing-Changes-to-Jamf-Pro#required-permissions
